# SITE CONFIGURATION
title: TSAI's Blog # your site title
author: TSAI # You :P
description: > # Meta description of Homepage
Travel, Study, Everything In My Life.
baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "https://TsaiTsai2000.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: TSAI
  links:
    - https://www.facebook.com/ben.balter
    - https://www.facebook.com/wl03078162
    - https://github.com/TsaiTsai2000

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  分享生活、旅遊記事，把握現在的日子留做以後懷念。

hero_img: posts/cover.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: wl03078162@gmail.com # email for form submission

github_username: TsaiTsai2000  # replace with your_github_username or comment to remove link from footer
instagram_username: sincih0822 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: TSAI # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
